# Generated by Django 4.2.20 on 2025-04-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_upvote_total', models.IntegerField(default=0)),
                ('product_downvote_total', models.IntegerField(default=0)),
                ('product_comment_total', models.IntegerField(default=0)),
                ('product_interaction_total', models.IntegerField(default=0)),
                ('product_report_total', models.IntegerField(default=0)),
                ('product_total_score', models.FloatField()),
                ('product_is_trending', models.BooleanField(default=False)),
                ('product_is_featured', models.BooleanField(default=False)),
                ('product_is_promoted', models.BooleanField(default=False)),
                ('product_is_controversial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('safety_question', models.CharField(max_length=255)),
                ('safety_answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.TextField()),
                ('user_lastname', models.TextField()),
                ('user_date_of_birth', models.DateField()),
                ('user_age', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_security_email', models.EmailField(max_length=254)),
                ('user_phone_number', models.CharField(max_length=20)),
                ('user_bio', models.TextField()),
                ('total_entries_by_user', models.IntegerField(default=0)),
                ('total_likes_by_user', models.IntegerField(default=0)),
                ('total_comments_by_user', models.IntegerField(default=0)),
                ('total_interaction_by_user', models.IntegerField(default=0)),
                ('total_likes_received_by_user', models.IntegerField(default=0)),
                ('total_comments_received_by_user', models.IntegerField(default=0)),
                ('total_interactions_received_by_user', models.IntegerField(default=0)),
                ('user_score', models.FloatField()),
                ('user_is_trending', models.BooleanField(default=False)),
                ('user_is_featured', models.BooleanField(default=False)),
                ('user_is_affiliate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('upvote_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.TextField()),
                ('review_score', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('downvote_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
