# Generated by Django 4.2.20 on 2025-08-26 13:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.TextField(default='')),
                ('user_lastname', models.TextField(default='')),
                ('user_age', models.IntegerField(default=0)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_security_email', models.EmailField(default='', max_length=254)),
                ('user_phone_number', models.CharField(default='', max_length=20)),
                ('user_bio', models.TextField(default='')),
                ('total_entries_by_user', models.IntegerField(default=0)),
                ('total_upvotes_by_user', models.IntegerField(default=0)),
                ('total_downvotes_by_user', models.IntegerField(default=0)),
                ('total_reviews_by_user', models.IntegerField(default=0)),
                ('total_comments_by_user', models.IntegerField(default=0)),
                ('total_reports_by_user', models.IntegerField(default=0)),
                ('total_interaction_by_user', models.IntegerField(default=0)),
                ('total_upvotes_received_by_user', models.IntegerField(default=0)),
                ('total_downvotes_received_by_user', models.IntegerField(default=0)),
                ('total_comments_received_by_user', models.IntegerField(default=0)),
                ('total_reports_received_by_user', models.IntegerField(default=0)),
                ('total_interactions_received_by_user', models.IntegerField(default=0)),
                ('user_score', models.FloatField(default=0)),
                ('user_is_trending', models.BooleanField(default=False)),
                ('user_is_featured', models.BooleanField(default=False)),
                ('user_is_affiliate', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255)),
                ('product_description', models.TextField(default='')),
                ('product_category', models.CharField(choices=[('productivity_tools', 'Productivity Tools'), ('mobile_accessories', 'Mobile Accessories'), ('smart_home_essentials', 'Smart Home Essentials'), ('gaming_accessories', 'Gaming Accessories'), ('audio_accessories', 'Audio Accessories'), ('camera_accessories', 'Camera Accessories'), ('office_essentials', 'Office Essentials'), ('travel_essentials', 'Travel Essentials'), ('health_and_fitness', 'Health and Fitness'), ('home_and_garden', 'Home and Garden'), ('other', 'Other')], default='other', max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_link', models.URLField(blank=True, help_text='Link to purchase the product', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_upvote_count', models.IntegerField(default=0)),
                ('product_downvote_count', models.IntegerField(default=0)),
                ('product_comment_count', models.IntegerField(default=0)),
                ('product_interaction_count', models.IntegerField(default=0)),
                ('product_report_count', models.IntegerField(default=0)),
                ('product_average_rating', models.FloatField(default=0)),
                ('product_score', models.FloatField(default=0)),
                ('product_is_trending', models.BooleanField(default=False)),
                ('product_is_featured', models.BooleanField(default=False)),
                ('product_is_promoted', models.BooleanField(default=False)),
                ('product_is_controversial', models.BooleanField(default=False)),
                ('product_is_new', models.BooleanField(default=False)),
                ('product_is_popular', models.BooleanField(default=False)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('upvote_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('review_title', models.CharField(default='', max_length=255)),
                ('review_content', models.TextField(default='')),
                ('review_score', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('downvote_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField(default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
