# Generated by Django 4.2.20 on 2025-05-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_comment_total',
            new_name='product_comment_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_downvote_total',
            new_name='product_downvote_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_interaction_total',
            new_name='product_interaction_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_report_total',
            new_name='product_report_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_upvote_total',
            new_name='product_upvote_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='review_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_date_of_birth',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lastname',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_security_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
