# Generated by Django 4.2.23 on 2025-09-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='review_score',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='review_content',
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
