# Generated by Django 4.2.20 on 2025-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_product_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_likes_by_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_likes_received_by_user',
        ),
        migrations.AddField(
            model_name='user',
            name='total_downvotes_by_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_downvotes_received_by_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_reports_by_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_reports_received_by_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_reviews_by_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_upvotes_by_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_upvotes_received_by_user',
            field=models.IntegerField(default=0),
        ),
    ]
