# Generated by Django 4.2.20 on 2025-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
