# Generated by Django 4.2.20 on 2025-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
