# Generated by Django 4.2.20 on 2025-08-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_product_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_total_score',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('productivity_tools', 'Productivity Tools'), ('mobile_accessories', 'Mobile Accessories'), ('smart_home_essentials', 'Smart Home Essentials'), ('gaming_accessories', 'Gaming Accessories'), ('audio_accessories', 'Audio Accessories'), ('camera_accessories', 'Camera Accessories'), ('office_essentials', 'Office Essentials'), ('travel_essentials', 'Travel Essentials'), ('health_and_fitness', 'Health and Fitness'), ('home_and_garden', 'Home and Garden'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, help_text='Link to purchase the product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_score',
            field=models.FloatField(default=0),
        ),
    ]
